encoder_class: PlaceholderEncoder
encoder_parameters: {}
model_class: SingleValueBinarySelectionModel
model_hyperparameters: {}
serialization_version: 0
training_hyperparameters:
  learning_rate: 0.001
