encoder_class: PlaceholderEncoder
encoder_parameters: {}
model_class: SingleValueBinarySelectionModel
model_hyperparameters: {}
serialization_version: 0
training_hyperparameters:
  batch_size: 1024
  learning_rate: 0.001
  min_learning_rate: 1.0e-06
  optimizer_name: RMSprop
  weight_decay: 1.0e-06
