encoder_class: PlaceholderEncoder
encoder_parameters: {}
model_class: TransformerBinarySelectionModelWiggleAct
model_hyperparameters:
  d_model_per_head: 4
  dim_feedforward: 4096
  dropout_prob: 0.1
  layer_count: 5
  nhead: 8
serialization_version: 0
training_hyperparameters:
  batch_size: 1024
  l2_regularization_coeff: 1.0e-06
  learning_rate: 0.001
  min_learning_rate: 1.0e-06
  optimizer_name: AdamW
